apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
stringData:
  JwtSettings__SecretKey: "5n6FzPQ8i1M+93fDd9VmtQv5s0RUkV6a7hO2NHR6d7LJ3cs6j2QKeP+QJnbZr0yF" # e.g. 64+ chars
  JwtSettings__Issuer: "bsoft-auth"
  JwtSettings__Audience: "bsoft-api"
  JwtSettings__ExpiryMinutes: "1440"
