apiVersion: v1
kind: Secret
metadata:
  name: background-secrets
type: Opaque
stringData:
  DATABASE_SERVER: "192.168.1.126"
  DATABASE_USERID: "developer"
  DATABASE_PASSWORD: "Dev@#$456"
  MassTransit__RabbitMq__Host: "rabbitmq"
  MassTransit__RabbitMq__Username: "guest"
  MassTransit__RabbitMq__Password: "guest"
