apiVersion: v1
kind: Secret
metadata:
  name: saga-secrets
  namespace: default
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Server=192.168.1.126;Database=SagaDb;User Id=sa;Password=YourPassword@123;"
  Jwt__Key: "your-super-secret-jwt-key"
  Jwt__Issuer: "bsoft.saga"
  Jwt__Audience: "bsoft.all"
  RabbitMq__Host: "rabbitmq"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
