apiVersion: v1
kind: Service
metadata:
  name: saga-service
  labels:
    app: saga
    app.kubernetes.io/name: saga
    app.kubernetes.io/component: orchestrator
spec:
  selector:
    app: saga
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5192 # cluster port
      targetPort: http # <-- match the container port name
      nodePort: 30592 # external node port
    - name: grpc
      protocol: TCP
      port: 7278
      targetPort: grpc # <-- match the container port name
      nodePort: 30778
      appProtocol: grpc # <-- optional hint for gRPC
