apiVersion: v1
kind: Secret
metadata:
  name: maintenance-secrets
  namespace: default
type: Opaque
stringData:
  # 🔐 DB credentials for Maintenance service (plaintext here; kubectl will store as base64)
  DATABASE_SERVER: "192.168.1.126"
  DATABASE_USERID: "developer"
  DATABASE_PASSWORD: "Dev@#$456"
