syntax = "proto3";

import "google/protobuf/empty.proto";

option csharp_namespace = "GrpcServices.BackgroundService";

service ApprovalRequestStatusAllService {
    rpc GetApprovalRequestStatusAll (ApprovalStatusRequest) returns (ApprovalStatusAllListResponse);
}
message ApprovalStatusRequest {
    string ModuleTypeName = 1;
}
message ApprovalRequestStatusDto {
    int32 ModuleTransactionId = 1;
    int32 ApprovalRequestId = 2;
    string CurrentStatus = 3;
    string ModuleTypeName = 4;
}

message ApprovalStatusAllListResponse {
    repeated ApprovalRequestStatusDto approvalstatus = 1;
}