// party.proto
syntax = "proto3";
option csharp_namespace = "GrpcServices.Party.Party";
package party.party;

service PartyService {
  rpc GetPartyAutoComplete (PartyRequest) returns (PartyResponse);
  rpc GetPartyById         (GetPartyByIdRequest) returns (PartyDto);    
}

message PartyRequest { string search = 1; }
message GetPartyByIdRequest { int32 id = 1; }

message PartyResponse { repeated PartyDto items = 1; }

message PartyDto {
  int32 id = 1;
  string partyCode = 2;
  string partyName = 3;
}
