syntax = "proto3";

import "google/protobuf/empty.proto";

option csharp_namespace = "GrpcServices.PartyManagement";

service PartyService {
    rpc GetAllPartyMaster (google.protobuf.Empty) returns (PartyListResponse);
}

message PartyDto {
    int32 partyId = 1;
    string partyCode = 2;
    string partyName = 3;
    int32 registrationTypeId = 4;
    string gSTNumber = 5;
    string gSTStateCode = 6;
    string pan = 7;
    string tan = 8;
    string msmeno = 9;
    int32 isTDSApplicable = 10;
    int32 isTCSApplicable = 11;
    int32 isGstReverseCharge = 12;    
    int32 creditDays = 13;    
    string partyStatus = 14;
}

message PartyListResponse {
    repeated PartyDto parties = 1;
}
